### ISSUE TITLE
error when trainning "invalid literal for int() with base 10: ' '  "

### ISSUE THREAD

**Issue by xuzhang5788** [gitter-lab/pria_lifechem#27]
When I used 
python sklearn_randomforest.py --config_json_file=../../json/sklearn_randomforest.json --model_dir=$results_and_model_directory --dataset_dir=$path_to_dataset --process_num=$process --stage=0

to train random forest models, I got the following error message:  
Traceback (most recent call last):
  File "sklearn_randomforest.py", line 151, in <module>
    process_num = int(given_args.process_num)
ValueError: invalid literal for int() with base 10: ' '

I found given_args.process_num is a space ' ', so it can not be changed into an integer. Any advice? Many thanks.

**Comment by chao1224** [comment]
Hi @xuzhang5788 , the `process_num` in `sklearn_randomforest.py` specifies the hyparameter id, [these lines](https://github.com/gitter-lab/pria_lifechem/blob/master/pria_lifechem/models/sklearn_randomforest.py#L33-L52) is selecting the hyperparameter given the `process id`.

You can find all the possible hyperparameters for random forest in this [json file](https://github.com/gitter-lab/pria_lifechem/blob/master/json/sklearn_randomforest.json#L4-L7), which includes `3*3*4*3 = 108` hyperparameters in all. In other words, `process_num` can range from 0 to 107.

**Comment by xuzhang5788** [comment]
Thank you for your fast response. I still didn't get it. Do I need to modify this comment to run?

python sklearn_randomforest.py --config_json_file=../../json/sklearn_randomforest.json --model_dir=$results_and_model_directory --dataset_dir=$path_to_dataset --process_num=$process --stage=0

**Comment by chao1224** [comment]
Can you post the complete bash script? I'm not sure what's the `"$process"` here. (But if you set it from 0 to 107, it should work)

**Comment by xuzhang5788** [comment]
The bash script is from your readme file 
https://github.com/gitter-lab/pria_lifechem/tree/master/pria_lifechem/models

**Comment by chao1224** [comment]
You need to specify the variables in the bash env

```
export process_num=0
export path_to_dataset=/dir/to/the/dataset

python sklearn_randomforest.py \
--config_json_file=../../json/sklearn_randomforest.json \
--model_dir=$results_and_model_directory \
--dataset_dir=$path_to_dataset \
--process_num=$process \
--stage=1
```

**Comment by Malnammi** [comment]
Just to clarify. There are a total 108 hyperparameter combinations for the RandomForest in `sklearn_randomforest.json`. The script `sklearn_randomforest.py` , selects one of these using the `process_num` argument. So you need to set `process_num` to the hyperparameter index you want. 

For example, one of the 8 RF hyperparameters that were promoted to the CV stage was index: `12`. So, to run for index 12:

```
python sklearn_randomforest.py \
--config_json_file=../../json/sklearn_randomforest.json \
--model_dir=./folder_to_store_results/  \
--dataset_dir=./path_to_csv_files/ \
--process_num=12 \
--stage=1
```

Set `model_dir` to a folder path you'd like to store the results. Set `dataset_dir` to the folder path where the `[file_0.csv, file_1.csv, ..., file_4.csv]` data files are.

**Comment by xuzhang5788** [comment]
@chao1224 @Malnammi 
Thank you so much.
